services:
  server:
    build:
      context: .
    environment:
      SECRET: $ecret.key
      NODE_ENV: production
      CORS_ORIGIN: "*"
      MAXNUMBER: 5000
    ports:
      - 3000:3000
      - 8080:8080
